from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager
from flask.ext.sqlalchemy import SQLAlchemy

from config import config
from .moment import momentjs

bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    app.jinja_env.globals['momentjs'] = momentjs

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .scenario import scenario as scenario_blueprint
    app.register_blueprint(scenario_blueprint, url_prefix='/scenario')

    from .zoning import zoning as zoning_blueprint
    app.register_blueprint(zoning_blueprint, url_prefix='/zoning')

    return app


zoning_definitions = {
'1_Beach': {'jurisdiction_id': 1,'zone_code': 'Beach','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-1': {'jurisdiction_id': 1,'zone_code': 'C-1','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-1-Q': {'jurisdiction_id': 1,'zone_code': 'C-1-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-2': {'jurisdiction_id': 1,'zone_code': 'C-2','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-2-Q': {'jurisdiction_id': 1,'zone_code': 'C-2-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-L': {'jurisdiction_id': 1,'zone_code': 'C-L','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-M': {'jurisdiction_id': 1,'zone_code': 'C-M','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-T': {'jurisdiction_id': 1,'zone_code': 'C-T','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-T-Q': {'jurisdiction_id': 1,'zone_code': 'C-T-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-T-Q/C-2-Q': {'jurisdiction_id': 1,'zone_code': 'C-T-Q/C-2-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-T-Q/OS': {'jurisdiction_id': 1,'zone_code': 'C-T-Q/OS','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_C-T-Q/RD-M-Q': {'jurisdiction_id': 1,'zone_code': 'C-T-Q/RD-M-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_E-A': {'jurisdiction_id': 1,'zone_code': 'E-A','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 40,'max_front_setback': 0,'rear_setback': 0,'side_setback': 15,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_E-A-Q': {'jurisdiction_id': 1,'zone_code': 'E-A-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 40,'max_front_setback': 0,'rear_setback': 0,'side_setback': 15,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_L-C': {'jurisdiction_id': 1,'zone_code': 'L-C','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_M': {'jurisdiction_id': 1,'zone_code': 'M','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_M-Q': {'jurisdiction_id': 1,'zone_code': 'M-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_O': {'jurisdiction_id': 1,'zone_code': 'O','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_O-Q/P-M-Q': {'jurisdiction_id': 1,'zone_code': 'O-Q/P-M-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_OS': {'jurisdiction_id': 1,'zone_code': 'OS','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_P-C': {'jurisdiction_id': 1,'zone_code': 'P-C','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_P-M': {'jurisdiction_id': 1,'zone_code': 'P-M','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 35,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_P-M-Q': {'jurisdiction_id': 1,'zone_code': 'P-M-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 35,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_P-M/O': {'jurisdiction_id': 1,'zone_code': 'P-M/O','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_P-U': {'jurisdiction_id': 1,'zone_code': 'P-U','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_R-1': {'jurisdiction_id': 1,'zone_code': 'R-1','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 6.64286,'min_dua': 0,'max_dua': 5.808,'max_building_height': 0},
'1_R-1-0.5Q': {'jurisdiction_id': 1,'zone_code': 'R-1-0.5Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 51.3333,'min_dua': 0,'max_dua': 2,'max_building_height': 0},
'1_R-1-10000': {'jurisdiction_id': 1,'zone_code': 'R-1-10000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 8.45,'min_dua': 0,'max_dua': 4.356,'max_building_height': 0},
'1_R-1-10000-Q': {'jurisdiction_id': 1,'zone_code': 'R-1-10000-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 6.25,'min_dua': 0,'max_dua': 4.356,'max_building_height': 0},
'1_R-1-15000': {'jurisdiction_id': 1,'zone_code': 'R-1-15000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10.6667,'min_dua': 0,'max_dua': 2.904,'max_building_height': 0},
'1_R-1-20000': {'jurisdiction_id': 1,'zone_code': 'R-1-20000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 13.5,'min_dua': 0,'max_dua': 2.178,'max_building_height': 0},
'1_R-1-25000': {'jurisdiction_id': 1,'zone_code': 'R-1-25000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10.85,'min_dua': 0,'max_dua': 1.7424,'max_building_height': 0},
'1_R-1-30000': {'jurisdiction_id': 1,'zone_code': 'R-1-30000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 11.2,'min_dua': 0,'max_dua': 1.452,'max_building_height': 0},
'1_R-1-8000': {'jurisdiction_id': 1,'zone_code': 'R-1-8000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 6.52,'min_dua': 0,'max_dua': 5.445,'max_building_height': 0},
'1_R-1-9000': {'jurisdiction_id': 1,'zone_code': 'R-1-9000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.5,'min_dua': 0,'max_dua': 4.84,'max_building_height': 0},
'1_R-1-9500': {'jurisdiction_id': 1,'zone_code': 'R-1-9500','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 8.475,'min_dua': 0,'max_dua': 4.58526,'max_building_height': 0},
'1_R-1-Q': {'jurisdiction_id': 1,'zone_code': 'R-1-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 6.41429,'min_dua': 0,'max_dua': 5.808,'max_building_height': 0},
'1_R-2': {'jurisdiction_id': 1,'zone_code': 'R-2','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 6.43333,'min_dua': 0,'max_dua': 8,'max_building_height': 0},
'1_R-3': {'jurisdiction_id': 1,'zone_code': 'R-3','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5.06667,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_R-3-Q': {'jurisdiction_id': 1,'zone_code': 'R-3-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 27.1667,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_R-A': {'jurisdiction_id': 1,'zone_code': 'R-A','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_R-A-10000': {'jurisdiction_id': 1,'zone_code': 'R-A-10000','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.4,'min_dua': 0,'max_dua': 4.356,'max_building_height': 0},
'1_R-A-10000-Q': {'jurisdiction_id': 1,'zone_code': 'R-A-10000-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.98,'min_dua': 0,'max_dua': 4.356,'max_building_height': 0},
'1_R-A-2.5': {'jurisdiction_id': 1,'zone_code': 'R-A-2.5','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 37,'min_dua': 0,'max_dua': 0.4,'max_building_height': 0},
'1_R-E': {'jurisdiction_id': 1,'zone_code': 'R-E','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 70,'max_front_setback': 0,'rear_setback': 0,'side_setback': 15,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'1_R-P': {'jurisdiction_id': 1,'zone_code': 'R-P','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.1,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_R-P-Q': {'jurisdiction_id': 1,'zone_code': 'R-P-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_R-P-Q/C-T-Q': {'jurisdiction_id': 1,'zone_code': 'R-P-Q/C-T-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_R-T': {'jurisdiction_id': 1,'zone_code': 'R-T','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_R-W': {'jurisdiction_id': 1,'zone_code': 'R-W','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 10,'max_front_setback': 0,'rear_setback': 0,'side_setback': 4,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_RD-M': {'jurisdiction_id': 1,'zone_code': 'RD-M','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_RD-M-Q': {'jurisdiction_id': 1,'zone_code': 'RD-M-Q','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 23,'max_building_height': 0},
'1_RD-M/R-3': {'jurisdiction_id': 1,'zone_code': 'RD-M/R-3','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_RMHP': {'jurisdiction_id': 1,'zone_code': 'RMHP','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 5,'max_front_setback': 0,'rear_setback': 0,'side_setback': 3,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_T-C': {'jurisdiction_id': 1,'zone_code': 'T-C','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_Trans': {'jurisdiction_id': 1,'zone_code': 'Trans','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'1_V-R': {'jurisdiction_id': 1,'zone_code': 'V-R','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_C': {'jurisdiction_id': 3,'zone_code': 'C','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_CR': {'jurisdiction_id': 3,'zone_code': 'CR','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_CU': {'jurisdiction_id': 3,'zone_code': 'CU','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_HM': {'jurisdiction_id': 3,'zone_code': 'HM','region_id': 1,'min_far': 0,'max_far': 1.8,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_JIA': {'jurisdiction_id': 3,'zone_code': 'JIA','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_MZ': {'jurisdiction_id': 3,'zone_code': 'MZ','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_OS': {'jurisdiction_id': 3,'zone_code': 'OS','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_R-1A': {'jurisdiction_id': 3,'zone_code': 'R-1A','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 8,'max_building_height': 0},
'3_R-1A(BF)': {'jurisdiction_id': 3,'zone_code': 'R-1A(BF)','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 6,'max_building_height': 0},
'3_R-1A(CC-1)': {'jurisdiction_id': 3,'zone_code': 'R-1A(CC-1)','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 8,'max_building_height': 0},
'3_R-1A(CC-2)': {'jurisdiction_id': 3,'zone_code': 'R-1A(CC-2)','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 8,'max_building_height': 0},
'3_R-1A(CC-3)': {'jurisdiction_id': 3,'zone_code': 'R-1A(CC-3)','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 8,'max_building_height': 0},
'3_R-1A(E)': {'jurisdiction_id': 3,'zone_code': 'R-1A(E)','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 6,'max_dua': 8,'max_building_height': 0},
'3_R-1B': {'jurisdiction_id': 3,'zone_code': 'R-1B','region_id': 1,'min_far': 0,'max_far': 0.64,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 12,'max_building_height': 0},
'3_R-3': {'jurisdiction_id': 3,'zone_code': 'R-3','region_id': 1,'min_far': 0,'max_far': 0.9,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 28,'max_building_height': 0},
'3_R-3/P': {'jurisdiction_id': 3,'zone_code': 'R-3/P','region_id': 1,'min_far': 0,'max_far': 0.9,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 28,'max_building_height': 0},
'3_R-4': {'jurisdiction_id': 3,'zone_code': 'R-4','region_id': 1,'min_far': 0,'max_far': 1.6,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 40,'max_building_height': 0},
'3_R-4/CU': {'jurisdiction_id': 3,'zone_code': 'R-4/CU','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_R-5': {'jurisdiction_id': 3,'zone_code': 'R-5','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 47,'max_building_height': 0},
'3_RPCD': {'jurisdiction_id': 3,'zone_code': 'RPCD','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_RSCD': {'jurisdiction_id': 3,'zone_code': 'RSCD','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_Trans': {'jurisdiction_id': 3,'zone_code': 'Trans','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'3_Water': {'jurisdiction_id': 3,'zone_code': 'Water','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_BC': {'jurisdiction_id': 4,'zone_code': 'BC','region_id': 1,'min_far': 0,'max_far': 0.1,'min_front_setback': 10,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'4_CC': {'jurisdiction_id': 4,'zone_code': 'CC','region_id': 1,'min_far': 0,'max_far': 0.45,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_CVPP': {'jurisdiction_id': 4,'zone_code': 'CVPP','region_id': 1,'min_far': 0,'max_far': 0.65,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_FR': {'jurisdiction_id': 4,'zone_code': 'FR','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_FW': {'jurisdiction_id': 4,'zone_code': 'FW','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_HSP': {'jurisdiction_id': 4,'zone_code': 'HSP','region_id': 1,'min_far': 0,'max_far': 0.65,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_NC': {'jurisdiction_id': 4,'zone_code': 'NC','region_id': 1,'min_far': 0,'max_far': 0.3,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_PC': {'jurisdiction_id': 4,'zone_code': 'PC','region_id': 1,'min_far': 0,'max_far': 0.6,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_PF': {'jurisdiction_id': 4,'zone_code': 'PF','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_PP': {'jurisdiction_id': 4,'zone_code': 'PP','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_PSP': {'jurisdiction_id': 4,'zone_code': 'PSP','region_id': 1,'min_far': 0,'max_far': 0.65,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_R1-10': {'jurisdiction_id': 4,'zone_code': 'R1-10','region_id': 1,'min_far': 0,'max_far': 0.25,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.5,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'4_R1-10B': {'jurisdiction_id': 4,'zone_code': 'R1-10B','region_id': 1,'min_far': 0,'max_far': 0.3,'min_front_setback': 10,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'4_R1-14': {'jurisdiction_id': 4,'zone_code': 'R1-14','region_id': 1,'min_far': 0,'max_far': 0.25,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 7.5,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'4_R1-15': {'jurisdiction_id': 4,'zone_code': 'R1-15','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_R1-15B': {'jurisdiction_id': 4,'zone_code': 'R1-15B','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_R1-40': {'jurisdiction_id': 4,'zone_code': 'R1-40','region_id': 1,'min_far': 0,'max_far': 0.125,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 1,'max_building_height': 0},
'4_R2': {'jurisdiction_id': 4,'zone_code': 'R2','region_id': 1,'min_far': 0,'max_far': 0.35,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 12.5,'max_building_height': 0},
'4_RC': {'jurisdiction_id': 4,'zone_code': 'RC','region_id': 1,'min_far': 0,'max_far': 0.3,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 12.5,'max_building_height': 0},
'4_RM-Central': {'jurisdiction_id': 4,'zone_code': 'RM-Central','region_id': 1,'min_far': 0,'max_far': 0.3,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 9.4,'max_building_height': 0},
'4_RM-East': {'jurisdiction_id': 4,'zone_code': 'RM-East','region_id': 1,'min_far': 0,'max_far': 0.4,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 11.2,'max_building_height': 0},
'4_RM-South': {'jurisdiction_id': 4,'zone_code': 'RM-South','region_id': 1,'min_far': 0,'max_far': 0.35,'min_front_setback': 20,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 11.7,'max_building_height': 0},
'4_RM-West': {'jurisdiction_id': 4,'zone_code': 'RM-West','region_id': 1,'min_far': 0,'max_far': 0.45,'min_front_setback': 10,'max_front_setback': 0,'rear_setback': 0,'side_setback': 5,'min_dua': 0,'max_dua': 11.2,'max_building_height': 0},
'4_ROAD': {'jurisdiction_id': 4,'zone_code': 'ROAD','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_RR': {'jurisdiction_id': 4,'zone_code': 'RR','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_VC': {'jurisdiction_id': 4,'zone_code': 'VC','region_id': 1,'min_far': 0,'max_far': 0.4,'min_front_setback': 10,'max_front_setback': 0,'rear_setback': 0,'side_setback': 10,'min_dua': 0,'max_dua': 0,'max_building_height': 0},
'4_Water': {'jurisdiction_id': 4,'zone_code': 'Water','region_id': 1,'min_far': 0,'max_far': 0,'min_front_setback': 0,'max_front_setback': 0,'rear_setback': 0,'side_setback': 0,'min_dua': 0,'max_dua': 0,'max_building_height': 0}
}

allowed_use_def = {
1: {'zoning_id': '1_C-1', 'development_type_id': 4},
2: {'zoning_id': '1_C-1', 'development_type_id': 5},
3: {'zoning_id': '1_C-1-Q', 'development_type_id': 21},
4: {'zoning_id': '1_C-1-Q', 'development_type_id': 4},
5: {'zoning_id': '1_C-1-Q', 'development_type_id': 5},
6: {'zoning_id': '1_C-2', 'development_type_id': 19},
7: {'zoning_id': '1_C-2', 'development_type_id': 2},
8: {'zoning_id': '1_C-2', 'development_type_id': 21},
9: {'zoning_id': '1_C-2', 'development_type_id': 4},
10: {'zoning_id': '1_C-2', 'development_type_id': 5},
11: {'zoning_id': '1_C-2', 'development_type_id': 7},
12: {'zoning_id': '1_C-2-Q', 'development_type_id': 16},
13: {'zoning_id': '1_C-2-Q', 'development_type_id': 2},
14: {'zoning_id': '1_C-2-Q', 'development_type_id': 21},
15: {'zoning_id': '1_C-2-Q', 'development_type_id': 4},
16: {'zoning_id': '1_C-2-Q', 'development_type_id': 5},
17: {'zoning_id': '1_C-L', 'development_type_id': 13},
18: {'zoning_id': '1_C-L', 'development_type_id': 16},
19: {'zoning_id': '1_C-L', 'development_type_id': 21},
20: {'zoning_id': '1_C-L', 'development_type_id': 4},
21: {'zoning_id': '1_C-L', 'development_type_id': 5},
22: {'zoning_id': '1_C-M', 'development_type_id': 14},
23: {'zoning_id': '1_C-M', 'development_type_id': 16},
24: {'zoning_id': '1_C-M', 'development_type_id': 2},
25: {'zoning_id': '1_C-M', 'development_type_id': 4},
26: {'zoning_id': '1_C-M', 'development_type_id': 5},
27: {'zoning_id': '1_C-M', 'development_type_id': 7},
28: {'zoning_id': '1_C-T', 'development_type_id': 19},
29: {'zoning_id': '1_C-T', 'development_type_id': 21},
30: {'zoning_id': '1_C-T', 'development_type_id': 4},
31: {'zoning_id': '1_C-T', 'development_type_id': 5},
32: {'zoning_id': '1_C-T', 'development_type_id': 7},
33: {'zoning_id': '1_C-T-Q', 'development_type_id': 13},
34: {'zoning_id': '1_C-T-Q', 'development_type_id': 14},
35: {'zoning_id': '1_C-T-Q', 'development_type_id': 5},
36: {'zoning_id': '1_C-T-Q', 'development_type_id': 7},
37: {'zoning_id': '1_C-T-Q', 'development_type_id': 8},
38: {'zoning_id': '1_C-T-Q/C-2-Q', 'development_type_id': 5},
39: {'zoning_id': '1_C-T-Q/C-2-Q', 'development_type_id': 7},
40: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 19},
41: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 2},
42: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 21},
43: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 4},
44: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 5},
45: {'zoning_id': '1_C-T-Q/RD-M-Q', 'development_type_id': 7},
46: {'zoning_id': '1_E-A', 'development_type_id': 2},
47: {'zoning_id': '1_E-A-Q', 'development_type_id': 19},
48: {'zoning_id': '1_L-C', 'development_type_id': 1},
49: {'zoning_id': '1_L-C', 'development_type_id': 12},
50: {'zoning_id': '1_L-C', 'development_type_id': 19},
51: {'zoning_id': '1_L-C', 'development_type_id': 8},
52: {'zoning_id': '1_L-C', 'development_type_id': 9},
53: {'zoning_id': '1_M', 'development_type_id': 1},
54: {'zoning_id': '1_M', 'development_type_id': 2},
55: {'zoning_id': '1_M', 'development_type_id': 21},
56: {'zoning_id': '1_M', 'development_type_id': 4},
57: {'zoning_id': '1_M', 'development_type_id': 6},
58: {'zoning_id': '1_M-Q', 'development_type_id': 2},
59: {'zoning_id': '1_M-Q', 'development_type_id': 4},
60: {'zoning_id': '1_O', 'development_type_id': 2},
61: {'zoning_id': '1_O', 'development_type_id': 4},
62: {'zoning_id': '1_O-Q/P-M-Q', 'development_type_id': 4},
63: {'zoning_id': '1_P-C', 'development_type_id': 1},
64: {'zoning_id': '1_P-C', 'development_type_id': 12},
65: {'zoning_id': '1_P-C', 'development_type_id': 13},
66: {'zoning_id': '1_P-C', 'development_type_id': 14},
67: {'zoning_id': '1_P-C', 'development_type_id': 15},
68: {'zoning_id': '1_P-C', 'development_type_id': 16},
69: {'zoning_id': '1_P-C', 'development_type_id': 19},
70: {'zoning_id': '1_P-C', 'development_type_id': 2},
71: {'zoning_id': '1_P-C', 'development_type_id': 20},
72: {'zoning_id': '1_P-C', 'development_type_id': 21},
73: {'zoning_id': '1_P-C', 'development_type_id': 4},
74: {'zoning_id': '1_P-C', 'development_type_id': 5},
75: {'zoning_id': '1_P-C', 'development_type_id': 6},
76: {'zoning_id': '1_P-C', 'development_type_id': 7},
77: {'zoning_id': '1_P-C', 'development_type_id': 8},
78: {'zoning_id': '1_P-C', 'development_type_id': 9},
79: {'zoning_id': '1_P-M', 'development_type_id': 15},
80: {'zoning_id': '1_P-M', 'development_type_id': 16},
81: {'zoning_id': '1_P-M', 'development_type_id': 2},
82: {'zoning_id': '1_P-M', 'development_type_id': 4},
83: {'zoning_id': '1_P-M', 'development_type_id': 5},
84: {'zoning_id': '1_P-M', 'development_type_id': 6},
85: {'zoning_id': '1_P-M', 'development_type_id': 7},
86: {'zoning_id': '1_P-M-Q', 'development_type_id': 2},
87: {'zoning_id': '1_P-M-Q', 'development_type_id': 4},
88: {'zoning_id': '1_P-M/O', 'development_type_id': 2},
89: {'zoning_id': '1_P-U', 'development_type_id': 1},
90: {'zoning_id': '1_P-U', 'development_type_id': 2},
91: {'zoning_id': '1_P-U', 'development_type_id': 5},
92: {'zoning_id': '1_R-1', 'development_type_id': 1},
93: {'zoning_id': '1_R-1', 'development_type_id': 13},
94: {'zoning_id': '1_R-1', 'development_type_id': 15},
95: {'zoning_id': '1_R-1', 'development_type_id': 16},
96: {'zoning_id': '1_R-1', 'development_type_id': 19},
97: {'zoning_id': '1_R-1', 'development_type_id': 2},
98: {'zoning_id': '1_R-1', 'development_type_id': 20},
99: {'zoning_id': '1_R-1', 'development_type_id': 21},
100: {'zoning_id': '1_R-1', 'development_type_id': 4},
101: {'zoning_id': '1_R-1', 'development_type_id': 8},
102: {'zoning_id': '1_R-1', 'development_type_id': 9},
103: {'zoning_id': '1_R-1-0.5Q', 'development_type_id': 19},
104: {'zoning_id': '1_R-1-10000', 'development_type_id': 1},
105: {'zoning_id': '1_R-1-10000', 'development_type_id': 14},
106: {'zoning_id': '1_R-1-10000', 'development_type_id': 15},
107: {'zoning_id': '1_R-1-10000', 'development_type_id': 19},
108: {'zoning_id': '1_R-1-10000', 'development_type_id': 20},
109: {'zoning_id': '1_R-1-10000', 'development_type_id': 8},
110: {'zoning_id': '1_R-1-10000-Q', 'development_type_id': 1},
111: {'zoning_id': '1_R-1-10000-Q', 'development_type_id': 19},
112: {'zoning_id': '1_R-1-10000-Q', 'development_type_id': 20},
113: {'zoning_id': '1_R-1-10000-Q', 'development_type_id': 21},
114: {'zoning_id': '1_R-1-15000', 'development_type_id': 19},
115: {'zoning_id': '1_R-1-15000', 'development_type_id': 2},
116: {'zoning_id': '1_R-1-15000', 'development_type_id': 20},
117: {'zoning_id': '1_R-1-20000', 'development_type_id': 16},
118: {'zoning_id': '1_R-1-25000', 'development_type_id': 19},
119: {'zoning_id': '1_R-1-25000', 'development_type_id': 20},
120: {'zoning_id': '1_R-1-30000', 'development_type_id': 19},
121: {'zoning_id': '1_R-1-30000', 'development_type_id': 20},
122: {'zoning_id': '1_R-1-8000', 'development_type_id': 1},
123: {'zoning_id': '1_R-1-8000', 'development_type_id': 16},
124: {'zoning_id': '1_R-1-8000', 'development_type_id': 19},
125: {'zoning_id': '1_R-1-8000', 'development_type_id': 20},
126: {'zoning_id': '1_R-1-9000', 'development_type_id': 19},
127: {'zoning_id': '1_R-1-9500', 'development_type_id': 1},
128: {'zoning_id': '1_R-1-9500', 'development_type_id': 19},
129: {'zoning_id': '1_R-1-9500', 'development_type_id': 2},
130: {'zoning_id': '1_R-1-9500', 'development_type_id': 20},
131: {'zoning_id': '1_R-1-Q', 'development_type_id': 1},
132: {'zoning_id': '1_R-1-Q', 'development_type_id': 13},
133: {'zoning_id': '1_R-1-Q', 'development_type_id': 19},
134: {'zoning_id': '1_R-1-Q', 'development_type_id': 20},
135: {'zoning_id': '1_R-2', 'development_type_id': 19},
136: {'zoning_id': '1_R-2', 'development_type_id': 20},
137: {'zoning_id': '1_R-2', 'development_type_id': 21},
138: {'zoning_id': '1_R-3', 'development_type_id': 12},
139: {'zoning_id': '1_R-3', 'development_type_id': 13},
140: {'zoning_id': '1_R-3', 'development_type_id': 16},
141: {'zoning_id': '1_R-3', 'development_type_id': 19},
142: {'zoning_id': '1_R-3', 'development_type_id': 20},
143: {'zoning_id': '1_R-3', 'development_type_id': 21},
144: {'zoning_id': '1_R-3', 'development_type_id': 4},
145: {'zoning_id': '1_R-3', 'development_type_id': 7},
146: {'zoning_id': '1_R-3', 'development_type_id': 8},
147: {'zoning_id': '1_R-3-Q', 'development_type_id': 19},
148: {'zoning_id': '1_R-3-Q', 'development_type_id': 21},
149: {'zoning_id': '1_R-3-Q', 'development_type_id': 8},
150: {'zoning_id': '1_R-A-10000', 'development_type_id': 1},
151: {'zoning_id': '1_R-A-10000', 'development_type_id': 19},
152: {'zoning_id': '1_R-A-10000', 'development_type_id': 2},
153: {'zoning_id': '1_R-A-10000', 'development_type_id': 20},
154: {'zoning_id': '1_R-A-10000', 'development_type_id': 6},
155: {'zoning_id': '1_R-A-10000-Q', 'development_type_id': 19},
156: {'zoning_id': '1_R-A-2.5', 'development_type_id': 19},
157: {'zoning_id': '1_R-E', 'development_type_id': 1},
158: {'zoning_id': '1_R-E', 'development_type_id': 19},
159: {'zoning_id': '1_R-P', 'development_type_id': 12},
160: {'zoning_id': '1_R-P', 'development_type_id': 19},
161: {'zoning_id': '1_R-P', 'development_type_id': 20},
162: {'zoning_id': '1_R-P', 'development_type_id': 21},
163: {'zoning_id': '1_R-P', 'development_type_id': 4},
164: {'zoning_id': '1_R-P', 'development_type_id': 5},
165: {'zoning_id': '1_R-P', 'development_type_id': 7},
166: {'zoning_id': '1_R-P', 'development_type_id': 8},
167: {'zoning_id': '1_R-P-Q', 'development_type_id': 1},
168: {'zoning_id': '1_R-P-Q', 'development_type_id': 16},
169: {'zoning_id': '1_R-P-Q', 'development_type_id': 19},
170: {'zoning_id': '1_R-P-Q', 'development_type_id': 20},
171: {'zoning_id': '1_R-P-Q', 'development_type_id': 4},
172: {'zoning_id': '1_R-T', 'development_type_id': 19},
173: {'zoning_id': '1_R-T', 'development_type_id': 20},
174: {'zoning_id': '1_R-T', 'development_type_id': 21},
175: {'zoning_id': '1_R-T', 'development_type_id': 5},
176: {'zoning_id': '1_R-T', 'development_type_id': 7},
177: {'zoning_id': '1_R-W', 'development_type_id': 19},
178: {'zoning_id': '1_R-W', 'development_type_id': 20},
179: {'zoning_id': '1_R-W', 'development_type_id': 21},
180: {'zoning_id': '1_RD-M', 'development_type_id': 12},
181: {'zoning_id': '1_RD-M', 'development_type_id': 13},
182: {'zoning_id': '1_RD-M', 'development_type_id': 15},
183: {'zoning_id': '1_RD-M', 'development_type_id': 16},
184: {'zoning_id': '1_RD-M', 'development_type_id': 19},
185: {'zoning_id': '1_RD-M', 'development_type_id': 20},
186: {'zoning_id': '1_RD-M', 'development_type_id': 21},
187: {'zoning_id': '1_RD-M', 'development_type_id': 4},
188: {'zoning_id': '1_RD-M', 'development_type_id': 5},
189: {'zoning_id': '1_RD-M-Q', 'development_type_id': 1},
190: {'zoning_id': '1_RD-M-Q', 'development_type_id': 15},
191: {'zoning_id': '1_RD-M-Q', 'development_type_id': 19},
192: {'zoning_id': '1_RD-M-Q', 'development_type_id': 2},
193: {'zoning_id': '1_RD-M-Q', 'development_type_id': 20},
194: {'zoning_id': '1_RD-M-Q', 'development_type_id': 21},
195: {'zoning_id': '1_RD-M-Q', 'development_type_id': 4},
196: {'zoning_id': '1_RD-M-Q', 'development_type_id': 5},
197: {'zoning_id': '1_RD-M-Q', 'development_type_id': 6},
198: {'zoning_id': '1_RD-M-Q', 'development_type_id': 7},
199: {'zoning_id': '1_RD-M-Q', 'development_type_id': 8},
200: {'zoning_id': '1_RMHP', 'development_type_id': 1},
201: {'zoning_id': '1_RMHP', 'development_type_id': 15},
202: {'zoning_id': '1_RMHP', 'development_type_id': 22},
203: {'zoning_id': '1_V-R', 'development_type_id': 12},
204: {'zoning_id': '1_V-R', 'development_type_id': 13},
205: {'zoning_id': '1_V-R', 'development_type_id': 15},
206: {'zoning_id': '1_V-R', 'development_type_id': 16},
207: {'zoning_id': '1_V-R', 'development_type_id': 19},
208: {'zoning_id': '1_V-R', 'development_type_id': 2},
209: {'zoning_id': '1_V-R', 'development_type_id': 20},
210: {'zoning_id': '1_V-R', 'development_type_id': 21},
211: {'zoning_id': '1_V-R', 'development_type_id': 4},
212: {'zoning_id': '1_V-R', 'development_type_id': 5},
213: {'zoning_id': '1_V-R', 'development_type_id': 7},
214: {'zoning_id': '1_V-R', 'development_type_id': 9},
3115: {'zoning_id': '3_C', 'development_type_id': 13},
3116: {'zoning_id': '3_C', 'development_type_id': 16},
3117: {'zoning_id': '3_C', 'development_type_id': 21},
3118: {'zoning_id': '3_C', 'development_type_id': 4},
3119: {'zoning_id': '3_C', 'development_type_id': 5},
3120: {'zoning_id': '3_C', 'development_type_id': 7},
3121: {'zoning_id': '3_CR', 'development_type_id': 14},
3122: {'zoning_id': '3_CR', 'development_type_id': 15},
3123: {'zoning_id': '3_CR', 'development_type_id': 2},
3124: {'zoning_id': '3_CR', 'development_type_id': 5},
3125: {'zoning_id': '3_CU', 'development_type_id': 12},
3126: {'zoning_id': '3_CU', 'development_type_id': 15},
3127: {'zoning_id': '3_CU', 'development_type_id': 16},
3128: {'zoning_id': '3_CU', 'development_type_id': 2},
3129: {'zoning_id': '3_CU', 'development_type_id': 8},
3130: {'zoning_id': '3_CU', 'development_type_id': 9},
3131: {'zoning_id': '3_HM', 'development_type_id': 15},
3132: {'zoning_id': '3_HM', 'development_type_id': 16},
3133: {'zoning_id': '3_HM', 'development_type_id': 7},
3134: {'zoning_id': '3_R-1A', 'development_type_id': 19},
3135: {'zoning_id': '3_R-1A', 'development_type_id': 20},
3136: {'zoning_id': '3_R-1A', 'development_type_id': 21},
3137: {'zoning_id': '3_R-1A(BF)', 'development_type_id': 19},
3138: {'zoning_id': '3_R-1A(BF)', 'development_type_id': 20},
3139: {'zoning_id': '3_R-1A(CC-1)', 'development_type_id': 19},
3140: {'zoning_id': '3_R-1A(CC-1)', 'development_type_id': 20},
3141: {'zoning_id': '3_R-1A(CC-2)', 'development_type_id': 19},
3142: {'zoning_id': '3_R-1A(CC-3)', 'development_type_id': 19},
3143: {'zoning_id': '3_R-1A(CC-3)', 'development_type_id': 2},
3144: {'zoning_id': '3_R-1A(E)', 'development_type_id': 19},
3145: {'zoning_id': '3_R-1A(E)', 'development_type_id': 20},
3146: {'zoning_id': '3_R-1B', 'development_type_id': 13},
3147: {'zoning_id': '3_R-1B', 'development_type_id': 19},
3148: {'zoning_id': '3_R-1B', 'development_type_id': 2},
3149: {'zoning_id': '3_R-1B', 'development_type_id': 20},
3150: {'zoning_id': '3_R-1B', 'development_type_id': 21},
3151: {'zoning_id': '3_R-3', 'development_type_id': 13},
3152: {'zoning_id': '3_R-3', 'development_type_id': 16},
3153: {'zoning_id': '3_R-3', 'development_type_id': 19},
3154: {'zoning_id': '3_R-3', 'development_type_id': 2},
3155: {'zoning_id': '3_R-3', 'development_type_id': 20},
3156: {'zoning_id': '3_R-3', 'development_type_id': 21},
3157: {'zoning_id': '3_R-3', 'development_type_id': 4},
3158: {'zoning_id': '3_R-3', 'development_type_id': 5},
3159: {'zoning_id': '3_R-3', 'development_type_id': 7},
3160: {'zoning_id': '3_R-3', 'development_type_id': 8},
3161: {'zoning_id': '3_R-3/P', 'development_type_id': 13},
3162: {'zoning_id': '3_R-3/P', 'development_type_id': 19},
3163: {'zoning_id': '3_R-3/P', 'development_type_id': 20},
3164: {'zoning_id': '3_R-3/P', 'development_type_id': 21},
3165: {'zoning_id': '3_R-3/P', 'development_type_id': 4},
3166: {'zoning_id': '3_R-3/P', 'development_type_id': 5},
3167: {'zoning_id': '3_R-3/P', 'development_type_id': 7},
3168: {'zoning_id': '3_R-4', 'development_type_id': 13},
3169: {'zoning_id': '3_R-4', 'development_type_id': 16},
3170: {'zoning_id': '3_R-4', 'development_type_id': 19},
3171: {'zoning_id': '3_R-4', 'development_type_id': 2},
3172: {'zoning_id': '3_R-4', 'development_type_id': 20},
3173: {'zoning_id': '3_R-4', 'development_type_id': 21},
3174: {'zoning_id': '3_R-4', 'development_type_id': 5},
3175: {'zoning_id': '3_R-4', 'development_type_id': 7},
3176: {'zoning_id': '3_R-5', 'development_type_id': 21},
3177: {'zoning_id': '3_RPCD', 'development_type_id': 15},
3178: {'zoning_id': '3_RPCD', 'development_type_id': 21},
3179: {'zoning_id': '4_BC', 'development_type_id': 14},
3180: {'zoning_id': '4_BC', 'development_type_id': 19},
3181: {'zoning_id': '4_BC', 'development_type_id': 5},
3182: {'zoning_id': '4_CC', 'development_type_id': 4},
3183: {'zoning_id': '4_CC', 'development_type_id': 5},
3184: {'zoning_id': '4_CVPP', 'development_type_id': 15},
3185: {'zoning_id': '4_CVPP', 'development_type_id': 19},
3186: {'zoning_id': '4_FR', 'development_type_id': 14},
3187: {'zoning_id': '4_HSP', 'development_type_id': 7},
3188: {'zoning_id': '4_NC', 'development_type_id': 4},
3189: {'zoning_id': '4_PC', 'development_type_id': 4},
3190: {'zoning_id': '4_PF', 'development_type_id': 16},
3191: {'zoning_id': '4_PF', 'development_type_id': 2},
3192: {'zoning_id': '4_PF', 'development_type_id': 8},
3193: {'zoning_id': '4_PF', 'development_type_id': 9},
3194: {'zoning_id': '4_PSP', 'development_type_id': 5},
3195: {'zoning_id': '4_R1-10', 'development_type_id': 19},
3196: {'zoning_id': '4_R1-10', 'development_type_id': 2},
3197: {'zoning_id': '4_R1-10', 'development_type_id': 20},
3198: {'zoning_id': '4_R1-10B', 'development_type_id': 19},
3199: {'zoning_id': '4_R1-10B', 'development_type_id': 20},
3200: {'zoning_id': '4_R1-14', 'development_type_id': 19},
3201: {'zoning_id': '4_R1-14', 'development_type_id': 5},
3202: {'zoning_id': '4_R1-40', 'development_type_id': 15},
3203: {'zoning_id': '4_R1-40', 'development_type_id': 19},
3204: {'zoning_id': '4_R1-40', 'development_type_id': 20},
3205: {'zoning_id': '4_R2', 'development_type_id': 19},
3206: {'zoning_id': '4_R2', 'development_type_id': 20},
3207: {'zoning_id': '4_R2', 'development_type_id': 21},
3208: {'zoning_id': '4_R2', 'development_type_id': 5},
3209: {'zoning_id': '4_R2', 'development_type_id': 7},
3210: {'zoning_id': '4_RC', 'development_type_id': 19},
3211: {'zoning_id': '4_RC', 'development_type_id': 20},
3212: {'zoning_id': '4_RC', 'development_type_id': 4},
3213: {'zoning_id': '4_RM-Central', 'development_type_id': 13},
3214: {'zoning_id': '4_RM-Central', 'development_type_id': 19},
3215: {'zoning_id': '4_RM-Central', 'development_type_id': 20},
3216: {'zoning_id': '4_RM-Central', 'development_type_id': 21},
3217: {'zoning_id': '4_RM-Central', 'development_type_id': 7},
3218: {'zoning_id': '4_RM-East', 'development_type_id': 19},
3219: {'zoning_id': '4_RM-East', 'development_type_id': 20},
3220: {'zoning_id': '4_RM-East', 'development_type_id': 21},
3221: {'zoning_id': '4_RM-South', 'development_type_id': 15},
3222: {'zoning_id': '4_RM-South', 'development_type_id': 19},
3223: {'zoning_id': '4_RM-South', 'development_type_id': 20},
3224: {'zoning_id': '4_RM-South', 'development_type_id': 21},
3225: {'zoning_id': '4_RM-West', 'development_type_id': 19},
3226: {'zoning_id': '4_RM-West', 'development_type_id': 20},
3227: {'zoning_id': '4_RM-West', 'development_type_id': 21},
3228: {'zoning_id': '4_VC', 'development_type_id': 7}
}

development_type_defs = {
    1: 'Agriculture and Mining',
    2: 'Light Industrial',
    3: 'Heavy Industrial',
    4: 'Office',
    5: 'Retail',
    6: 'Depot',
    7: 'Hotel / Motel',
    8: 'Primary Schools',
    9: 'Secondary Schools',
    10: 'Post-Secondary Institution',
    11: 'College Dormitory',
    12: 'Health Care',
    13: 'Religous',
    14: 'Recreation',
    15: 'Active Park',
    16: 'Government Operations',
    17: 'Dump Space',
    18: 'Mixed Use',
    19: 'Single-Family Detached Residential',
    20: 'Single-Family Attached Residential',
    21: 'Multi-Family Residential',
    22: 'Mobile Home',
    23: 'Military Residential (Non-GQ)',
    24: 'Transportation Right-of-Way',
    25: 'Parking Lot',
    26: 'Undeveloped Open Space',
    27: 'Beach',
    28: 'Water',
    29: 'Military Reservation',
    30: 'Native American Reservation',
    31: 'Vacant Developable Land'
}


model_structure_def = {
    1: {'name': 'scheduled_development_events',
        'display_name': 'Scheduled Development Events',
        'overview': '',
        'active': 0},
    2: {'name': 'neighborhood_vars',
        'display_name': 'Neighborhood and Proximity Variables',
        'overview': '',
        'active': 1},
    3: {'name': 'rsh_simulate',
        'display_name': 'Residential Hedonic Simulation',
        'overview': '',
        'active': 1},
    4: {'name': 'nrh_simulate',
        'display_name': 'Non-Residential Hedonic Simulation',
        'overview': ''},
        'active': 1,
    5: {'name': 'nrh2_simulate',
        'display_name': 'Non-Residential Hedonic Simulation 2',
        'overview': '',
        'active': 1},
    6: {'name': 'job_transition',
        'display_name': 'Job Transition',
        'overview': '',
        'active': 1},
    7: {'name': 'elcm_simulate',
        'display_name': 'Employment Location Choice',
        'overview': '',
        'active': 1},
    8: {'name': 'household_transition',
        'display_name': 'Household Transitions',
        'overview': '',
        'active': 1},
    9: {'name': 'hlcm_simulate',
        'display_name': 'Household Location Choice',
        'overview': '',
        'active': 1},
    10: {'name': 'price_vars',
        'display_name': 'Price Variables',
        'overview': '',
        'active': 1},
    11: {'name': 'feasibility',
         'display_name': 'Feasibility',
         'overview': '',
         'active': 1},
    12: {'name': 'residential_developer',
         'display_name': 'Residential Developer',
         'overview': '',
         'active': 1},
    13: {'name': 'non_residential_developer',
         'display_name': 'Non-Residential Developer',
         'overview': '',
         'active': 1}
}